<?php

namespace devmx\Teamspeak3\Query;

require_once dirname( __FILE__ ) . '/../../../../devmx/Teamspeak3/Query/Event.php';

/**
 * Test class for Event.
 * Generated by PHPUnit on 2011-11-07 at 21:42:29.
 */
class EventTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Event
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Event("foo",Array(Array()));

    }

   
    /**
 .
     */
    public function testGetReason()
    {
        $this->assertEquals("foo", $this->object->getReason());
    }

}

?>
