<?php

namespace devmx\Teamspeak3\Query\Transport\Decorator\Caching\Cache;

require_once dirname( __FILE__ ) . '/../../../../../../../../../src/devmx/Teamspeak3/Query/Transport/Decorator/Caching/Cache/DoctrineCommonProxy.php';

/**
 * Test class for DoctrineCommonProxy.
 * Generated by PHPUnit on 2012-06-24 at 17:25:21.
 */
class DoctrineCommonProxyTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var DoctrineCommonProxy
     */
    protected $cache;
    
    protected $doctrineCacheStub;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->doctrineCacheStub = $this->getMockForAbstractClass('\Doctrine\Common\Cache\Cache');
        $this->cache = new DoctrineCommonProxy($this->doctrineCacheStub, 123);        
    }

    /**
     * @covers devmx\Teamspeak3\Query\Transport\Decorator\Caching\Cache\DoctrineCommonProxy::getCache
     * @todo Implement testGetCache().
     */
    public function testGetCache()
    {
        $this->doctrineCacheStub->expects($this->once())
                                 ->method('fetch')
                                 ->with($this->equalTo('foo'))
                                 ->will($this->returnValue('bar'));
        $this->assertEquals('bar', $this->cache->getCache('foo'));
    }

    /**
     * @covers devmx\Teamspeak3\Query\Transport\Decorator\Caching\Cache\DoctrineCommonProxy::isCached
     * @todo Implement testIsCached().
     */
    public function testIsCached()
    {
        $this->doctrineCacheStub->expects($this->once())
                                ->method('contains')
                                ->with($this->equalTo('foo'))
                                ->will($this->returnValue(true));
        $this->assertTrue($this->cache->isCached('foo'));
    }

    /**
     * @covers devmx\Teamspeak3\Query\Transport\Decorator\Caching\Cache\DoctrineCommonProxy::cache
     * @todo Implement testCache().
     */
    public function testCache_defaultTTL()
    {
        $this->doctrineCacheStub->expects($this->once())
                                 ->method('save')
                                 ->with($this->equalTo('foo'), $this->equalTo('bar'), $this->equalTo(123));
        $this->cache->cache('foo', 'bar');
    }

    /**
     * @covers devmx\Teamspeak3\Query\Transport\Decorator\Caching\Cache\DoctrineCommonProxy::cache
     * @todo Implement testCache().
     */
    public function testCache_TTL()
    {
        $this->doctrineCacheStub->expects($this->once())
                                 ->method('save')
                                 ->with($this->equalTo('foo'), $this->equalTo('bar'), $this->equalTo(321));
        $this->cache->cache('foo', 'bar', 321);
    }
}

?>
