<?php

namespace devmx\Teamspeak3\Query\Transport\Decorator\Caching\Cache;

require_once dirname( __FILE__ ) . '/../../../../../../../../../src/devmx/Teamspeak3/Query/Transport/Decorator/Caching/Cache/NullCache.php';

/**
 * Test class for NullCache.
 * Generated by PHPUnit on 2012-05-16 at 16:14:25.
 */
class NullCacheTest extends \PHPUnit_Framework_TestCase
{

    public function testCache()
    {
        $cache = new NullCache();
        $this->assertTrue($cache->cache('asdf', new \DateTime()), 1234);
        $this->assertFalse($cache->isCached('asdf'));
        $this->assertFalse($cache->getCache('asdf'));
    }

}

?>
