<?php

namespace devmx\Teamspeak3\Query\Exception;

require_once dirname( __FILE__ ) . '/../../../../../../src/devmx/Teamspeak3/Query/Exception/BannedException.php';

/**
 * Test class for BannedException.
 * Generated by PHPUnit on 2012-06-23 at 14:35:35.
 */
class BannedExceptionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @covers devmx\Teamspeak3\Query\Exception\BannedException::getRetryTime
     * @covers devmx\Teamspeak3\Query\Exception\BannedException::__construct
     */
    public function testGetRetryTime()
    {
        $e = new BannedException(123);
        $this->assertEquals(123, $e->getRetryTime());
    }
    
    /**
     * @covers devmx\Teamspeak3\Query\Exception\BannedException::createMessage
     * @covers devmx\Teamspeak3\Query\Exception\BannedException::__construct
     */
    public function testMessage()
    {
        $e = new BannedException(123);
        $this->assertEquals('You got banned, retry in 123 seconds', $e->getMessage());
    }

}

?>
