<?php

namespace devmx\Teamspeak3\Query\Exception;
use devmx\Teamspeak3\Query\Response\CommandResponse;
use devmx\Teamspeak3\Query\Command;

/**
 * Test class for CommandFailedException.
 * Generated by PHPUnit on 2012-06-23 at 15:28:43.
 */
class CommandFailedExceptionTest extends \PHPUnit_Framework_TestCase
{   
    
    public function testGetResponse()
    {
        $response = new CommandResponse(new Command('use'));
        $e = new CommandFailedException($response);
        $this->assertEquals($response, $e->getResponse());
    }

}

?>
