<?php

namespace devmx\Teamspeak3\Query\Exception;

require_once dirname( __FILE__ ) . '/../../../../../../src/devmx/Teamspeak3/Query/Exception/ConnectionFailedException.php';

/**
 * Test class for ConnectionFailedException.
 * Generated by PHPUnit on 2012-06-24 at 16:23:17.
 */
class ConnectionFailedExceptionTest extends \PHPUnit_Framework_TestCase
{
    public function testCreation() {
        $e = new ConnectionFailedException('foo');
        $this->assertInstanceOf('devmx\Teamspeak3\Query\Exception\ExceptionInterface', $e);
    }
}

?>
