<?php

namespace devmx\Teamspeak3\Query\Exception;

/**
 * Test class for InvalidArgumentException.
 * Generated by PHPUnit on 2012-06-24 at 16:50:57.
 */
class InvalidArgumentExceptionTest extends \PHPUnit_Framework_TestCase
{
    public function testCreation() {
        $e = new InvalidArgumentException('asdf');
        $this->assertInstanceOf('devmx\Teamspeak3\Query\Exception\ExceptionInterface', $e);
    }
}

?>
