<?php

namespace devmx\Teamspeak3\Query\Exception;
use devmx\Teamspeak3\Query\Command;

/**
 * Test class for InvalidCommandException.
 * Generated by PHPUnit on 2012-06-24 at 16:25:41.
 */
class InvalidCommandExceptionTest extends \PHPUnit_Framework_TestCase
{
    
    /**
     * @covers devmx\Teamspeak3\Query\Exception\InvalidCommandException::getInvalidCommand
     * @covers devmx\Teamspeak3\Query\Exception\InvalidCommandException::getInvalidityType
     * @covers devmx\Teamspeak3\Query\Exception\InvalidCommandException::getInvalidValue
     */
    public function testGetters()
    {
        $command = new Command('foo');
        $e = new InvalidCommandException($command, InvalidCommandException::INVALID_NAME, 'foo');
        $this->assertEquals($command, $e->getInvalidCommand());
        $this->assertEquals(InvalidCommandException::INVALID_NAME, $e->getInvalidityType());
        $this->assertEquals('foo', $e->getInvalidValue());
    }
        
    /**
     * @covers devmx\Teamspeak3\Query\Exception\InvalidCommandException::__construct
     * @covers devmx\Teamspeak3\Query\Exception\InvalidCommandException::buildMessage
     * @covers devmx\Teamspeak3\Query\Exception\InvalidCommandException::convertToString 
     */
    public function testMessage() {
        $date = new \DateTime();
        $command = new Command($date);
        $e = new InvalidCommandException($command, InvalidCommandException::INVALID_NAME, $date);
        $this->assertEquals('Invalid command "<object of class "DateTime">" because name "<object of class "DateTime">" is invalid.', $e->getMessage());
    }

}

?>
