<?php

namespace devmx\Teamspeak3\Query\Exception;

require_once dirname( __FILE__ ) . '/../../../../../../src/devmx/Teamspeak3/Query/Exception/LogicException.php';

/**
 * Test class for LogicException.
 * Generated by PHPUnit on 2012-06-24 at 16:53:46.
 */
class LogicExceptionTest extends \PHPUnit_Framework_TestCase
{

    public function testCreation() {
        $e = new LogicException('asdf');
        $this->assertInstanceOf('devmx\Teamspeak3\Query\Exception\ExceptionInterface', $e);
    }

}

?>
