<?php

namespace devmx\Teamspeak3\Query\Exception;

/**
 * Test class for NotConnectedException.
 * Generated by PHPUnit on 2012-06-24 at 16:54:02.
 */
class NotConnectedExceptionTest extends \PHPUnit_Framework_TestCase
{

    public function testCreation() {
        $e = new NotConnectedException('asdf');
        $this->assertInstanceOf('devmx\Teamspeak3\Query\Exception\ExceptionInterface', $e);
    }

}

?>
