<?php

namespace devmx\Teamspeak3\Query\Exception;

require_once dirname( __FILE__ ) . '/../../../../../../src/devmx/Teamspeak3/Query/Exception/RuntimeException.php';

/**
 * Test class for RuntimeException.
 * Generated by PHPUnit on 2012-06-24 at 16:54:33.
 */
class RuntimeExceptionTest extends \PHPUnit_Framework_TestCase
{
    public function testCreation() {
        $e = new RuntimeException('asdf');
        $this->assertInstanceOf('devmx\Teamspeak3\Query\Exception\ExceptionInterface', $e);
    }
}

?>
