<?php

namespace devmx\Teamspeak3\Query\Transport\Decorator\Logging\Proxy;

require_once dirname( __FILE__ ) . '/../../../../../../../../../src/devmx/Teamspeak3/Query/Transport/Decorator/Logging/Proxy/MonologProxy.php';

/**
 * Test class for MonologProxy.
 * Generated by PHPUnit on 2012-06-24 at 17:36:24.
 */
class MonologProxyTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var MonologProxy
     */
    protected $logger;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->monologStub = $this->getMock('\Monolog\Logger', array(), array('logger'));
        $this->logger = new MonologProxy($this->monologStub);

    }

    /**
     * @covers devmx\Teamspeak3\Query\Transport\Decorator\Logging\Proxy\MonologProxy::addLog
     * @todo Implement testAddLog().
     */
    public function testAddLog()
    {
        $this->monologStub->expects($this->once())
                          ->method('addRecord')
                          ->with($this->equalTo(\Monolog\Logger::INFO), $this->equalTo('foo'));
        $this->logger->addLog('foo', \devmx\Teamspeak3\Query\Transport\Decorator\Logging\LoggingInterface::LOGGING_LEVEL_NOTICE);
    }

}

?>
