<?php

namespace devmx\Teamspeak3;

require_once dirname( __FILE__ ) . '/../../../../src/devmx/Teamspeak3/Server.php';

/**
 * Test class for Server.
 * Generated by PHPUnit on 2012-02-24 at 14:51:04.
 */
class ServerTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var \devmx\Teamspeak3\Server
     */
    protected $server;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->server = new Server;

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers devmx\Teamspeak3\Server::setValue
     * @covers devmx\Teamspeak3\Server::getValue
     */
    public function testSetGetValue()
    {
        $this->server->setValue('foo', 'bar');
        $this->assertEquals('bar', $this->server->getValue('foo'));
    }

    /**
     * @covers devmx\Teamspeak3\Server::offsetExists
     */
    public function testOffsetExists()
    {
        $this->server->setValue('foo','bar');
        $this->assertTrue(isset($this->server['foo']));
    }

    /**
     * @covers devmx\Teamspeak3\Server::offsetGet
     * @todo Implement testOffsetGet().
     */
    public function testOffsetGet()
    {
        $this->server->setValue('foo', 'bar');
        $this->assertEquals('bar', $this->server['foo']);
    }

    /**
     * @covers devmx\Teamspeak3\Server::offsetSet
     * @todo Implement testOffsetSet().
     */
    public function testOffsetSet()
    {
        $this->server['foo'] = 'bar';
        $this->assertEquals('bar', $this->server['foo']);
    }

    /**
     * @covers devmx\Teamspeak3\Server::getData
     */
    public function testGetData()
    {
        $this->server['foo'] = 'bar';
        $this->assertEquals(array('foo' => 'bar'), $this->server->getData());
    }

    /**
     * @covers devmx\Teamspeak3\Server::createVirtualServer
     * @todo Implement testCreateVirtualServer().
     */
    public function testCreateVirtualServer()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );

    }

    /**
     * @covers devmx\Teamspeak3\Server::deleteVirtualServer
     * @todo Implement testDeleteVirtualServer().
     */
    public function testDeleteVirtualServer()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );

    }

    /**
     * @covers devmx\Teamspeak3\Server::getVirtualServerByPort
     * @todo Implement testGetVirtualServerByPort().
     */
    public function testGetVirtualServerByPort()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );

    }

    /**
     * @covers devmx\Teamspeak3\Server::getVirtualServerByID
     * @todo Implement testGetVirtualServerByID().
     */
    public function testGetVirtualServerByID()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );

    }

    /**
     * @covers devmx\Teamspeak3\Server::stop
     * @todo Implement testStop().
     */
    public function testStop()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );

    }

    /**
     * @covers devmx\Teamspeak3\Server::findVirtualServer
     * @todo Implement testFindVirtualServer().
     */
    public function testFindVirtualServer()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );

    }

    /**
     * @covers devmx\Teamspeak3\Server::getVirtualServers
     * @todo Implement testGetVirtualServers().
     */
    public function testGetVirtualServers()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );

    }
}

?>
