<?php
namespace devmx\Teamspeak3;

/**
 * Test class for SimpleContainer.
 * Generated by PHPUnit on 2012-05-17 at 17:05:50.
 */
class SimpleContainerTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var SimpleContainer
     */
    protected $container;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->container = new SimpleContainer('example.com', 1234, true);
    }

    public function testCompleteCreation() {
        if(PHP_VERSION_ID >= 50312 && PHP_VERSION_ID < 50400) {
            //$this->markTestSkipped();
        }
        $this->assertInstanceOf('\devmx\Teamspeak3\Query\CommandAwareQuery', $this->container['query']);
        $this->assertInstanceOf('\devmx\Teamspeak3\Query\Transport\Decorator\DebuggingDecorator', $this->container['query.transport']);
    }

}

?>
