<?php

namespace devmx\Teamspeak3;

require_once dirname( __FILE__ ) . '/../../../../src/devmx/Teamspeak3/SimpleFactory.php';

/**
 * Test class for SimpleFactory.
 * Generated by PHPUnit on 2012-03-25 at 15:42:48.
 */
class SimpleFactoryTest extends \PHPUnit_Framework_TestCase
{
    
    /**
     *
     * @var \devmx\Teamspeak3\SimpleFactory
     */
    protected $factory;
    
    public function setUp() {
        $this->factory = new SimpleFactory('localhost', 20011, true);
    }

    public function testGetQuery()
    {
        $this->assertInstanceOf('\devmx\Teamspeak3\Query\ServerQuery', $this->factory->getQuery());
        $this->assertInstanceOf('\devmx\Teamspeak3\Query\QueryTransport', $this->factory->getQueryTransport(false));
    }
    
    public function testSingleObjectCreation() {
        $this->assertSame($this->factory->getQuery(), $this->factory->getQuery(), 'Two calls to getQuery should not create different objects');
    }
    
    public function testDebugDecoration() {
        $this->assertInstanceof('\devmx\Teamspeak3\Query\Transport\Decorator\DebuggingDecorator', $this->factory->getQueryTransport());
    }
    
    public function testGetProfilingDecorator() {
        $this->assertInstanceOf('\devmx\Teamspeak3\Query\Transport\Decorator\ProfilingDecorator', $this->factory->getProfilingDecorator());
    }

}

?>
