<?php

namespace devmx\Teamspeak3\Query;

 
/**
 * Test class for Event.
 * Generated by PHPUnit on 2011-11-07 at 21:42:29.
 */
class EventTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Event
     */
    protected $event;

    /**
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->event = new Event("foo",Array(Array()));

    }

    public function testGetReason()
    {
        $this->assertEquals("foo", $this->event->getReason());
    }

}

?>
