<?php

namespace devmx\Teamspeak3\Query\Response;
use devmx\Teamspeak3\Query\Command;

/**
 * Test class for HelpResponse.
 * Generated by PHPUnit on 2012-06-24 at 16:56:05.
 */
class HelpResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @covers devmx\Teamspeak3\Query\Response\HelpResponse::getHelpText
     * @covers devmx\Teamspeak3\Query\Response\HelpResponse::__construct
     */
    public function testGetHelpText()
    {
        $response = new HelpResponse(new Command('help'), 'this is not the help you are looking for');
        $this->assertEquals('this is not the help you are looking for', $response->getHelpText());
    }

}

?>
