<?php

namespace devmx\Teamspeak3\Query\Transport\Decorator\Caching;
use devmx\Teamspeak3\Query\Command;
use devmx\Teamspeak3\Query\CommandResponse;
use devmx\Teamspeak3\Query\CommandAwareQuery;

require_once dirname( __FILE__ ) . '/../../../../../../../../src/devmx/Teamspeak3/Query/Transport/Decorator/Caching/CachingDecorator.php';

/**
 * Test class for CachingDecorator.
 * Generated by PHPUnit on 2012-03-31 at 11:41:55.
 */
class CachingDecoratorTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var CachingDecorator
     */
    protected $decorator;
    
    /**
     * @var \devmx\Teamspeak3\Query\Transport\Decorator\Caching\CachingDecorator
     */
    protected $cache;
    
    /**
     * @var \devmx\Teamspeak3\Query\Transport\QueryTransportStub
     */
    protected $query;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->cache = $this->getMockForAbstractClass('\devmx\Teamspeak3\Query\Transport\Decorator\Caching\CacheInterface');
        $this->query = new \devmx\Teamspeak3\Query\Transport\QueryTransportStub();
        $this->decorator = new CachingDecorator($this->query, $this->cache);
    }
     
    public function testSendCommand_cache() {
        $this->decorator->setCacheableCommands(array('clientlist'));
        
        $cl_cmd = new Command('clientlist');
        $cl_r = new CommandResponse($cl_cmd);
        
        $this->query->addResponse($cl_r);
        
        $this->cache->expects($this->exactly(2))
                    ->method('isCached')
                    ->with(md5(serialize($cl_cmd)))
                    ->will($this->onConsecutiveCalls(false, true));
        
        $this->cache->expects($this->once())
                    ->method('cache')
                    ->with($this->equalTo(md5(serialize($cl_cmd))), $this->equalTo($cl_r));
        
        $this->cache->expects($this->once())
                    ->method('getCache')
                    ->with($this->equalto(md5(serialize($cl_cmd))))
                    ->will($this->returnValue($cl_r));
        
        $this->decorator->connect();
        $this->assertEquals($cl_r, $this->decorator->sendCommand($cl_cmd));
        $this->assertEquals($cl_r, $this->decorator->sendCommand($cl_cmd));
        
        $this->query->assertAllResponsesReceived();
    }

    /**
     * @covers devmx\Teamspeak3\Query\Transport\Decorator\Caching\CachingDecorator::getCacheAbleCommands
     * @todo Implement testGetCacheAbleCommands().
     */
    public function testSetGetCacheAbleCommands()
    {
        $this->decorator->setCacheableCommands(array('foo', 'bar'));
        $this->assertEquals(array('foo', 'bar'), $this->decorator->getCacheableCommands());
    }
    
    public function testDefaults() {
        $this->assertEquals(CommandAwareQuery::getNonChangingCommands(), $this->decorator->getCacheAbleCommands());
    }

}

?>
